# Generated by Django 2.1.5 on 2023-03-30 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20230328_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 30, 13, 40, 30, 990115, tzinfo=utc)),
        ),
    ]
